steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['test', 'soma']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/go-soma', '.']
- name: 'gcr.io/$PROJECT_ID/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/go-soma']

images: ['gcr.io/$PROJECT_ID/go-soma:latest'] 
tags: ['cloud-builders-community']